### ISSUE TITLE
[Feature] Spec Advice 

### ISSUE THREAD

**Issue by jake5691** [jake5691/Alfred-2.0#19]
Things to do:
- [x] clean up
- [x] make quicker 
- [ ] make cool user input thing
- [x] make available
- [ ] do Red Spec options
- [ ] bring across changes to drawings that Jake did in original
- [ ] proper watermark
- [ ] find the features achieved code I wrote and put it back in
- [x] fix Land so that it has tilehonour or tilespeed as dependency

**Comment by jj-jimjams** [comment]
Will close this issue and make the others separate items
