### ISSUE TITLE
Multi Server support

### ISSUE THREAD

**Issue by jake5691** [jake5691/Alfred-2.0#2]
Make it possible to have Alfred on multiple Servers. This requires:
- [ ] make static variables in `functions\staticValues.py` dynamic (changable from within discord)
- [ ] make features en/disable possible from within discord

**Comment by jake5691** [comment]
An idea of how to structure the settings of Alfred...


**Structure of Settings**
- Guild
   - Feature
       - enabled (y/n)
       - description
       - Commands
           - type (slash, command, on_message)
           - arguments
              - name
              - type (str, int, bool...)
           - name
           - description
           - allowed channels
           - allowed roles
           - excluded channels
           - excluded roles

**Comment by jj-jimjams** [comment]
It looks good.  I'm not sure how we'd then integrate that into the code - will probably copy what you do :)

When I've finished spec advice, I'm also going to add a subfolder so I can put them all in there as it's a bit messy at the moment.

Are we going to need a third Discord server to test this....?

**Comment by jake5691** [comment]
I'll work on it and let you know once I got it running how we can do it. But you can check the branch I created to see the current status...

But I somehow want to minimize the double effort will see if I can get it integrated nicely...

**Comment by jake5691** [comment]
And I got 3 more servers (for the wordle letter emojis) where the Alfred's are in, so can Test some stuff there...

Once it works it'll also be easy to merge to main because then it can be all the very same and no ID's have to be changed
