### ISSUE TITLE
[Feature] Move spec advice to Alfred so he's almost as cool as Lee

### ISSUE THREAD

**Issue by jj-jimjams** [jake5691/Alfred-2.0#23]
- [x] class
- [x] draw functions
- [x] useful/assign functions
- [x] blue definition (with fixes from Jake)
- [x] green definition (with fixes from Jake)
- [x] connection to discord

**Comment by jake5691** [comment]
I merged it to main #27 
seems to work :) 
So we can kick the Spec Advice bot from the server, right? - so far I only kicked it out of the spec advice channel
