### ISSUE TITLE
[BUG] replit can't find nextcord

### ISSUE THREAD

**Issue by jj-jimjams** [jake5691/Alfred-2.0#24]
**Describe the bug**
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    import nextcord
ModuleNotFoundError: No module named 'nextcord'

**To Reproduce**
try to run Dev repl.it

**Screenshots**

**Additional context**

**Comment by jake5691** [comment]
My previous fix was create a „.Replit" file and then delete it afterwards again.

But didn't work on dev version yesterday... will check when I get PC time after lunch....

**Comment by jake5691** [comment]
I created a bug ticket with the replit support. Hope they can help us to know what we do wrong...

**Comment by jake5691** [comment]
I managed to bring him to life again. 
What I did (things that might have played a role in solving it):
1. delete the `.replit` file (show hidden files if you can't see one, if still no there, create one and delete it after runnign Alfred once)
2. delete all files in the `package`section. (`poetry.lock` and `pyproject.toml`)
3. install `nextcord` again, it was removed by something I did

I did try starting Alfred in between a lot so will have to see what actually is necessary to get Alfred to work reliable after branch changes. We should then have the files that cause issues in the `.gitignore`so they don't get synced and therefor stay as they are. Downside might be that when new packages are needed or so they have to be installed manually after a branch change...
