### ISSUE TITLE
[BUG] Missing connections from center

### ISSUE THREAD

**Issue by jake5691** [jake5691/Alfred-2.0#25]
**Describe the bug**
In green and Blue spec picture the connection from center to first specs is missing

**To Reproduce**
Ask for Advice.

**Expected behavior**
Nice picture.

**Screenshots**
![image](https://user-images.githubusercontent.com/25382582/159332669-e2dd92ef-8bc5-45a1-9296-c63ee617ee49.jpeg)

**Comment by jj-jimjams** [comment]
I'm fixing this in the Alfred version :)  see #23
