### ISSUE TITLE
[Feature]spec advice enhancements

### ISSUE THREAD

**Issue by jj-jimjams** [jake5691/Alfred-2.0#30]
- [x] - slash commands for input
- [x] - more granular options for user input if they want
- [x] - have fun option (ie red spec)
- [x] - get ready for next season option
- [x] - first week option
- [x] - tile speed option or leader ability to select a priority that overrides preset options
- [x] - banner option
- [x] get translate for options
- [x] get spec level from loy/skill level db

**Comment by jake5691** [comment]
hint: in future  you can create a branch directly from within an issue. This will link it and name is set automatically to the issue title... ;)  
See the **Development** section on the right --->

**Comment by jj-jimjams** [comment]
I knew I could do that, I just couldn't remember how .... (thanks)

**Comment by jj-jimjams** [comment]
manual translation of preset and select options as the api was too slow for the command.  first week and next season option can be handled through leaderspec

**Comment by jj-jimjams** [comment]
complete
