### ISSUE TITLE
[BUG] wrong graphics are sent from Advice

### ISSUE THREAD

**Issue by jake5691** [jake5691/Alfred-2.0#32]
**Describe the bug**
The graphs are sent wrongly when multiple requests are sent in a short time.

**To Reproduce**
1. ask for advice quickly one after the other
2. the graph will be sent correct amount of time but not with the correct data 

**Expected behavior**
Every Advice gets its correct graphs.

**Screenshots**

![image](https://user-images.githubusercontent.com/25382582/159966981-1d39eeb0-fa1c-4719-aba6-7c64922f5f91.png)
![image](https://user-images.githubusercontent.com/25382582/159966996-4e686618-3659-43c2-a327-f2f0f94b8d48.png)

**Possible solution**
Give the graphs individual names when saving (add member name or such) and delete them after they are sent. That's how I do it with the keyboards

**Comment by jj-jimjams** [comment]
Fixed as per your suggestion (added userid to filename)
