### ISSUE TITLE
[BUG] translation of Advice keyword

### ISSUE THREAD

**Issue by jake5691** [jake5691/Alfred-2.0#33]
**Describe the bug**
Advice keyword is translated in the help. But the translation is not accepted as input
![image](https://user-images.githubusercontent.com/25382582/159967568-7c8009c6-7381-4626-aae6-e6d15038fe7f.png)

**Comment by jj-jimjams** [comment]
Hoping that this won't be needed once I've done the menus and buttons.  If I can't get it done this weekend, will do a fix for this.

**Comment by jake5691** [comment]
With rewrite of the Spec Advice this no longer is an issue
