### ISSUE TITLE
[Feature] Track Wonders lvl of all members

### ISSUE THREAD

**Issue by jake5691** [jake5691/Alfred-2.0#48]
I see 2 possibilities to make that happen:

1. Have a channel for each Wonder and have the input just like the loyalty and spec lvl -> just type in the number and it will update the ranking (this might be the easier way for everyone to use it, as some don't know Slash commands)
2. Make the input only possible via **Slash command** and then have all Wonder rankings in one channel. (This should be more robust and also with multi server in mind, easier to realize)
3. If we decide option 1 we can still have option 2 possible

@jj-jimjams what do you think will be the better option? Do you see other ways to do it?

**Comment by jj-jimjams** [comment]
could have keyword and input?  A single channel with buttons for each wonder? I see there is a text input component but I haven't figured out how to use it yet.  Or button with arrow up and down buttons to level?

**Comment by jj-jimjams** [comment]
slash commands mean translation is probably needed and I'm having issues with slow API response causing spec advice to fail at the moment;

**Comment by jake5691** [comment]
Buttons seam like a great idea :) 
I use the textInput (it's a textfield you can pass to a modal) for the adding values to variables in the settings (like adding replies to the random Reply command)

**Comment by jake5691** [comment]
open TODO:

- [ ] banner input
- [ ] show the rankings
- [ ] make the buttons view appear/reload after Alfred is restarted
- [ ] pic of the wonders as emoji
